---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: keyfactor-yaml-config
spec:
  profile: demo
  values:
    global:
      hub: thedemodrive
      tag: final-01
      imagePullPolicy: "Always"
      multiCluster:
        clusterName: FinalBuildCluster
      controlPlaneSecurityEnabled: true
      caProvider: "KeyfactorCA"
      caAddress: ""
      # Configure the external CA Provider by Keyfactor.
      keyfactor:
        ########
        # SecretName name of secret contain Keyfactor Credentials
        # Let empty for using yaml config
        # Each namespace must have one secret (pod only ready secret within namespace)
        secretName: ""
        # Name of certificate authorization
        caName: ""
        # Using for authentication header
        authToken: ""
        # ApiKey from Api Setting
        appKey: ""
        # Name of Keyfactor template
        caTemplate: "Istio"
        ########
        # Custom metadata fields attached to CSR request CSR enroll certificates
        # Remove from list if you dont need
        # Only support for: Cluster, Service, PodName, PodNameSpace, PodIP, TrustDomain.
        metadata:
          - name: Cluster # Do not modified it
            alias: Cluster # Name of custom metadata field on Keyfactor Platform
          - name: Service
            alias: Service
          # - name: PodName
          #   alias: PodName
          # - name: PodNamespace
          #   alias: PodNamespace
          # - name: PodIP
          #   alias: PodIP
          # - name: TrustDomain
          #   alias: TrustDomain

